<?php
error_reporting( -1 );
ini_set( 'display_errors', 1 );
# This file was automatically generated by the MediaWiki 1.39.5
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Dicionário de Favelas Marielle Franco";
$wgMetaNamespace = "Wikifavelas";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv('WG_SERVER');

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
#$wgLogos = [
#	'1x' => "/themes/images/logo_wikifavelas.svg",
#	'wordmark' => [
#		"src" => "/themes/images/logo_wikifavelas.svg",
#		"width" => 119,
#		"height" => 18,
#	],
#	'icon' => "/themes/images/logo_wikifavelas.svg",
#];
$wgLogos = [ '1x' => "$wgResourceBasePath/themes/images/logo_wikifavelas.svg" ];



## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "wikifavelas@fiocruz.br";
$wgPasswordSender = "wikifavelas@fiocruz.br";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = getenv('WG_DB_TYPE');
$wgDBserver = getenv('WG_DB_SERVER');
$wgDBname = getenv('WG_DB_NAME');
$wgDBuser = getenv('WG_DB_USER');
$wgDBpassword = getenv('WG_DB_PASSWORD');

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseCopyrightUpload = true;
$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "pt-br";

# Time zone
$wgLocaltimezone = "America/Sao_Paulo";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = getenv('WG_SECRET_KEY');

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = getenv('WG_UPGRADE_KEY');


## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = "Dicionário de Favelas Marielle Franco"; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "Creative Commons - Atribuição – Compartilhamento pela mesma Licença";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "chameleon";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'AbuseFilter' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'Form' );
wfLoadExtension( 'PageForms' );

# End of automatically generated settings.
# Add more configuration options below.
$wgShowExceptionDetails = true;

#VisualEditor
$wgGroupPermissions['user']['writeapi'] = true;
$wgVisualEditorSupportedSkins = ['*'];
$wgUsePathInfo = TRUE;

# Namespaces adicionais
define("NS_TESTES", 3000);
$wgExtraNamespaces[NS_TESTES] = "Testes";

# Ativar o VisualEditor em todos os namespaces
$wgVisualEditorAvailableNamespaces = array(
	NS_USER => true,
	NS_HELP => true,
	NS_PROJECT => true,
	NS_TESTES => true
);

# Semantic Wiki
// wfLoadExtension( 'SemanticMediaWiki' );
// enableSemantics( 'wikifavelas.com.br' );


#Extensões extras
wfLoadExtension( 'HeadScript' );
wfLoadExtension( 'HitCounters' );
wfLoadExtension( 'Iframe' );
wfLoadExtension( 'FontAwesome' );
wfLoadExtension( 'GeoData' );
wfLoadExtension( 'EmbedVideo' );
wfLoadExtension( 'InteractiveTimeline' );
wfLoadExtension( 'JsonConfig' );
wfLoadExtension( 'LabeledSectionTransclusion' );
wfLoadExtension( 'PDFEmbed' );
wfLoadExtension( 'Popups' );
wfLoadExtension( 'RandomPages' );
wfLoadExtension( 'RandomSelection' );
wfLoadExtension( 'UserExport' );
wfLoadExtension( 'WikiCategoryTagCloud' );
wfLoadExtension( 'WikiSEO' );
wfLoadExtension( 'ArticleRatings' );
wfLoadExtension( 'Disambiguator' );

#Easy Timeline
wfLoadExtension( 'timeline' );
$wgTimelineFontFile = 'ascii';

#Bootstrap
wfLoadExtension( 'Bootstrap' );

# LAYOUT
// Configurar Bootstrap
$wgHooks['SetupAfterCache'][] = function(){
	\Bootstrap\BootstrapManager::getInstance()->addAllBootstrapModules();
	return true;
};
$wgHooks['ParserAfterParse'][]=function( Parser &$parser, &$text, StripState &$stripState ){
	$parser->getOutput()->addModuleStyles( 'ext.bootstrap.styles' );
	$parser->getOutput()->addModules( 'ext.bootstrap.scripts' );
	return true;
};

#Bootstrap Components
wfLoadExtension( 'BootstrapComponents' );
$wgBootstrapComponentsWhitelist = true;
$wgBootstrapComponentsEnableCarouselGalleryMode = true;

# Enable subpages in the main namespace
$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_SPECIAL] = true;

# Enable subpages in the template namespace
$wgNamespacesWithSubpages[NS_TEMPLATE] = true;

// Ativar Skins alternativa com Mobile Frontend
wfLoadSkin( 'MinervaNeue' );
#wfLoadExtension( 'MobileFrontend' );
#wfLoadSkin( 'MinervaNeue' );
$wgMFDefaultSkinClass = 'SkinMinerva';

// Ativa o Chameleon e define como skin padrão
wfLoadSkin( 'chameleon' );
$wgDefaultSkin='chameleon';

// Definir layout Chameleon com navegação fixa para todo o site
$egChameleonLayoutFile= '/var/www/mediawiki/skins/chameleon/layouts/fixedhead.xml';

// Custom Chameleon bootstrap theme
$egChameleonThemeFile = '/var/www/mediawiki/themes/journal/_variables.scss';
$egChameleonExternalStyleModules = [
	'/var/www/mediawiki/themes/journal/_bootswatch.scss' => 'afterMain',
	
];

// Definir as esquema de estilos via variáveis do Chameleon 
$egChameleonExternalStyleVariables = [
    '$body-bg' => '#f4f6f9',
	'$cmln-navbar-bg-color' => 'dark',
	'$cmln-navbar-toggler-color' => 'light',
	'$cmln-search-bar-btn-color' => 'dark',
	'$cmln-personal-tools-link-new' =>	'("color": #FFF, "hover-color": #FFF)',
	'$cmln-navbar-logo-height' => '2.3rem',
	'$component-active-bg' => '#F27405',
	'$theme-colors' => '("primary": #62259c, "secondary": #6c757d, "success": #28a745, "info": #17a2b8, "warning": #ffc107, "danger": #dc3545, "light": #e9ecef, "dark": #343a40, "error": #dc3545, "darker": #ced4da)',
    '$cmln-link-formats' => "(new: ('color': #6E6E6E, 'hover-color': #FFA700 underline), stub: #f31d6c none #FF0089 underline,  extiw: #6B0CBC none #B607D6 underline, external:  #C7064E none #F7005C underline)",
	'$navbar-light-color' => '#FF8112',
	'$navbar-light-hover-color' => '#FFF',
	'$navbar-light-active-color' => '#FFF',
	'$enable-gradients' => '1',
];

// Enable external link icons
$egChameleonEnableExternalLinkIcons = true;

# Define the URL path of the shortcut icon.
$wgFavicon = '/themes/images/favicon.ico';

# DisplayTitle
$wgAllowDisplayTitle = true;
$wgRestrictDisplayTitle = false;

# Configuracoes comportamento links externos;
$wgExternalLinkTarget = '_blank';

#DynamicPageList
wfLoadExtension( 'intersection' );
# Configuration variables. Warning: These use DLP instead of DPL
# for historical reasons (pretend Dynamic list of pages)
$wgDLPmaxCategories = 6;                // Maximum number of categories to look for
$wgDLPMaxResultCount = 200;             // Maximum number of results to allow
$wgDLPAllowUnlimitedResults = false;    // Allow unlimited results
$wgDLPAllowUnlimitedCategories = false; // Allow unlimited categories
// How long to cache pages using DPL's in seconds. Default to 1 day. Set to
// false to use the normal amount of page caching (most efficient), Set to 0 to disable
// cache altogether (inefficient, but results will never be outdated)
$wgDLPMaxCacheTime = 60*60*24;          // How long to cache pages in seconds
$allowcachedresults = true;

# Configuracoes comportamento de Categorias
$wgCategoryMagicGallery = true;
$wgCategoryCollation = 'numeric';

# Habilitar palavra magica 
$wgAllowSlowParserFunctions = true;

# Configuracoes de e-mail
$wgSMTP = array(
	'host' => getenv('WG_SMTP_HOST'),
	'IDHost' => getenv('WG_SMTP_IDHOST'),
	'localhost' => getenv('WG_SMTP_LOCALHOST'),
	'port' => getenv('WG_SMTP_PORT'),
	'username' => getenv('WG_SMTP_USERNAME'),
	'password' => getenv('WG_SMTP_PASSWORD'),
	'auth' => getenv('WG_SMTP_AUTH'),
);
# Tornar email obrigatorio
$wgEmailConfirmToEdit = true;

# Enviar email de paginas vigiadas
$wgEnotifWatchlist = true;

# The permissions
$wgGroupPermissions['*']['edit'] = true;
# Ativar para Oficinas
$wgGroupPermissions['*']['noratelimit'] = true;
# Limite de criação de contas por IP
$wgAccountCreationThrottle = 40;

# Configuracoes do UserExport
$wgGroupPermissions['sysop']['userexport'] = true;

# Configuracoes de IFrame
$wgIframe['category'] = 'Iframe';
#$wgIframe['width'] = 800;
#$wgIframe['height'] = 600;
$wgIframe['server']['google'] = [ 'scheme' => 'https', 'domain' => 'www.google.com' ];
$wgIframe['server']['youtube'] = [ 'scheme' => 'https', 'domain' => 'www.youtube.com' ];
$wgIframe['server']['fiocruz'] = [ 'scheme' => 'https', 'domain' => 'faleconosco.fiocruz.br' ];
$wgIframe['server']['openstreetmap'] = [ 'scheme' => 'https', 'domain' => 'www.openstreetmap.org' ];
$wgIframe['server']['googledocs'] = [ 'scheme' => 'https',  'domain' => 'docs.google.com'];
$wgIframe['server']['arcgis'] = [ 'scheme' => 'https',  'domain' => 'www.arcgis.com'];
#$wgIframe['server']['mailchimp'] = [ 'scheme' => 'https', 'domain' => 'mailchi.mp' ];

# Configuracoes de PDF
// Default width for the PDF object container.
$wgPdfEmbed['width'] = 800;
// Default height for the PDF object container.
$wgPdfEmbed['height'] = 1090;
//Allow user the usage of the pdf tag
$wgGroupPermissions['*']['embed_pdf'] = true;


# For SVG image support
$wgFileExtensions = array_merge(
    $wgFileExtensions, [
        'pdf', 'svg' 
    ]
);
$wgSVGConverter = 'ImageMagick';
$wgAllowTitlesInSVG = true;

# Exibir vídeos
$wgEmbedVideoAddFileExtensions = true;
$wgEmbedVideoEnableVideoHandler = true;
$wgEmbedVideoEnableAudioHandler = true;

#Suprime aviso do EmbedVideo de funções deprecadas do PHP
$wgDeprecationReleaseLimit = '1.0'; 

# Configurar references
$wgCiteBookReferencing = true;
$wgCiteResponsiveReferences = true;

# Configuracoess HeadScript  Google tag (gtag.js)
$wgHeadScriptCode = <<<'START_END_MARKER'
<script async src="https://www.googletagmanager.com/gtag/js?id=G-CEJ4KDGYQN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-CEJ4KDGYQN');
</script>
START_END_MARKER;

#Ativar o Debug
$wgShowDebug = true;
$wgDevelopmentWarnings = true;
